---
# This task create coordinator database cluster for PostgreSQL-XL

- name: Generate coordinator database cluster
  shell: initdb -D {{ postgresql_data_dir }}/data_coord --nodename coord_{{ nodeName }}
  become: yes
  become_user: postgres

