---
# This Task deploy ssl certificate into dest machine

- name: Install openssl
  apt: name=openssl
  sudo: yes

- name: Install authorized_key file
  authorized_key: user={{ special_user }} state=present 
    key={{ lookup('file', 'id_rsa.pub') }}
  sudo: yes

- name: Copy private key file
  copy: src=id_rsa dest="/home/{{ special_user }}/.ssh/id_rsa" owner={{ special_user }}
    group={{ special_user }} mode=0600
  sudo: yes
